### ISSUE TITLE
ERROR: Compiling Fulan images

### ISSUE THREAD

**Issue by sid8796** [OpenVisionE2/meta-fulan#10]
Compiling Fulan images, please wait ...

Building image for adb_box
NOTE: Your conf/bblayers.conf has been automatically updated.
NOTE: Your conf/bblayers.conf has been automatically updated.
Loading cache: 100% |############################################| Time: 0:00:00
Loaded 3 entries from dependency cache.
WARNING: /home/sid8796/openpli-oe-core/meta-local/recipes-local/images/my-image.bb: Exception during build_dependencies for do_image_tar
WARNING: /home/sid8796/openpli-oe-core/meta-local/recipes-local/images/my-image.bb: Error during finalise of /home/sid8796/openpli-oe-core/meta-local/recipes-local/images/my-image.bb
ERROR: Unable to parse /home/sid8796/openpli-oe-core/meta-local/recipes-local/images/my-image.bb
Traceback (most recent call last):
  File "/home/sid8796/openpli-oe-core/bitbake/lib/bb/codeparser.py", line 370, in ShellParser._parse_shell(value='\t    ;     cp /home/sid8796/openpli-oe-core/build/tmp/deploy/images/adb_box/uImage /home/sid8796/openpli-oe-core/build/tmp/work/adb_box-oe-linux/my-image/1.0-r0/rootfs/boot/uImage;     tar -cvf /home/sid8796/openpli-oe-core/build/tmp/work/adb_box-oe-linux/my-image/1.0-r0/deploy-my-image-image-complete/openpli-enigma2-develop-7.0-r2-adb_box.rootfs.tar -C /home/sid8796/openpli-oe-core/build/tmp/work/adb_box-oe-linux/my-image/1.0-r0/rootfs .\n\tcd /home/sid8796/openpli-oe-core/build/tmp/work/adb_box-oe-linux/my-image/1.0-r0/deploy-my-image-image-complete\n\tgzip -f -9 -c openpli-enigma2-develop-7.0-r2-adb_box.rootfs.tar > openpli-enigma2-develop-7.0-r2-adb_box.rootfs.tar.gz\n\trm openpli-enigma2-develop-7.0-r2-adb_box.rootfs.tar'):
             try:
    >            tokens, _ = pyshyacc.parse(value, eof=True, debug=False)
             except pyshlex.NeedMore:
  File "/home/sid8796/openpli-oe-core/bitbake/lib/bb/pysh/pyshyacc.py", line 673, in parse(input='\t    ;     cp /home/sid8796/openpli-oe-core/build/tmp/deploy/images/adb_box/uImage /home/sid8796/openpli-oe-core/build/tmp/work/adb_box-oe-linux/my-image/1.0-r0/rootfs/boot/uImage;     tar -cvf /home/sid8796/openpli-oe-core/build/tmp/work/adb_box-oe-linux/my-image/1.0-r0/deploy-my-image-image-complete/openpli-enigma2-develop-7.0-r2-adb_box.rootfs.tar -C /home/sid8796/openpli-oe-core/build/tmp/work/adb_box-oe-linux/my-image/1.0-r0/rootfs .\n\tcd /home/sid8796/openpli-oe-core/build/tmp/work/adb_box-oe-linux/my-image/1.0-r0/deploy-my-image-image-complete\n\tgzip -f -9 -c openpli-enigma2-develop-7.0-r2-adb_box.rootfs.tar > openpli-enigma2-develop-7.0-r2-adb_box.rootfs.tar.gz\n\trm openpli-enigma2-develop-7.0-r2-adb_box.rootfs.tar', eof=True, debug=False):
             debug = 2
    >    return yacc.parse(lexer=lexer, debug=debug), remaining
     
  File "/home/sid8796/openpli-oe-core/bitbake/lib/ply/yacc.py", line 267, in LRParser.parse(input=None, lexer=<bb.pysh.pyshlex.PLYLexer object at 0x7f9fc241d9b0>, debug=False, tracking=0, tokenfunc=None):
             else:
    >            return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
             
  File "/home/sid8796/openpli-oe-core/bitbake/lib/ply/yacc.py", line 1049, in LRParser.parseopt_notrack(input=None, lexer=<bb.pysh.pyshlex.PLYLexer object at 0x7f9fc241d9b0>, debug=False, tracking=0, tokenfunc=None):
                                 errtoken.lexer = lexer
    >                        tok = self.errorfunc(errtoken)
                             del errok, token, restart   # Delete special functions
  File "/home/sid8796/openpli-oe-core/bitbake/lib/bb/pysh/pyshyacc.py", line 646, in p_error(p=LexToken(COMMA,';',0,0)):
             w('  %r\n' % n)
    >    raise sherrors.ShellSyntaxError(''.join(msg))
     
bb.pysh.sherrors.ShellSyntaxError: LexToken(COMMA,';',0,0)
followed by:
  LexToken(TOKEN,'cp',0,0)
  LexToken(TOKEN,'/home/sid8796/openpli-oe-core/build/tmp/deploy/images/adb_box/uImage',0,0)
  LexToken(TOKEN,'/home/sid8796/openpli-oe-core/build/tmp/work/adb_box-oe-linux/my-image/1.0-r0/rootfs/boot/uImage',0,0)
  LexToken(COMMA,';',0,0)
  LexToken(TOKEN,'tar',0,0)

Summary: There were 2 WARNING messages shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.
Makefile:125: recipe for target 'image' failed
make: *** [image] Error 1
Building image for arivalink200
Loading cache: 100% |############################################| Time: 0:00:00
Loaded 3 entries from dependency cache.
WARNING: /home/sid8796/openpli-oe-core/meta-local/recipes-local/images/my-image.bb: Exception during build_dependencies for do_image_tar
WARNING: /home/sid8796/openpli-oe-core/meta-local/recipes-local/images/my-image.bb: Error during finalise of /home/sid8796/openpli-oe-core/meta-local/recipes-local/images/my-image.bb
ERROR: Unable to parse /home/sid8796/openpli-oe-core/meta-local/recipes-local/images/my-image.bb

**Comment by backup1977** [comment]
I have the same problem

**Comment by backup1977** [comment]
Fixed
